### ISSUE TITLE
Вместо позывного DX отображается позывной споттера

### ISSUE THREAD

**Issue by R1BLH** [ExpertSDR3/ExpertSDR3-RadioSpot#2]
Поднял тестовый DX-кластер.
Отправил спот 5B4AOZ (см. на скриншот терминала):
![Screenshot_20230905_171450](https://github.com/ExpertSDR3/ExpertSDR3-RadioSpot/assets/16667173/ec98e6dc-9aae-4c25-ab3e-40fcca2d0e73)
На панораме EESDR3 отобразился мой позывной (R1BLH), а не позывной DX (см. скриншот EESDR3):
![Screenshot_20230905_171347](https://github.com/ExpertSDR3/ExpertSDR3-RadioSpot/assets/16667173/2a18dc14-d063-4993-92c7-4c5bed223ad1)

Есть подозрение, что с остальными кластерами происходит то же самое.

**Comment by ExpertSDR3** [comment]
Исправлено
